site_name: TestDoubles
docs_dir: ./documentation
site_dir: ./site
pages:
- Getting Started: index.md
- Cluster Mode: cluster_mode.md
- CLI Reference: CLI.md
- API Documentation: API.md
- Implementation Details: implementation_details.md
theme: mkdocs
